Add some compliance docs
Oneleet/oneleet-docs pull request #19
Opened 2024-12-07 01:40 UTC by sbysb

Adding three new pages to the 'guides' section

2025-02-05 08:05 UTC, mnafees requested changes

2025-02-05 08:05 UTC, mnafees commented on pages/guides/adapting-policies.mdx
> +# Adapting policies to your organization
```suggestion
---
title: Adapting policies to your organization
---

# Adapting policies to your organization
```

2025-02-05 08:05 UTC, mnafees commented on pages/guides/marketing-your-security.mdx
> +import {Tabs} from 'nextra/components'
```suggestion
---
title: Marketing your security
---

import {Tabs} from 'nextra/components'
```

2025-02-05 08:05 UTC, mnafees commented on pages/guides/personal-vs-company-workstations.mdx
> +# Personal vs company workstations
```suggestion
---
title: Personal vs company workstations
---

# Personal vs company workstations
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/marketing-your-security.mdx
> +We get it — working on compliance might not be the most exciting part of running a business. But here’s the thing: your hard work on compliance is not just about ticking boxes, especially here at One
```suggestion
We get it — working on compliance might not be the most exciting part of running a business. But here’s the thing: your hard work on compliance is not just about ticking boxes, especially here at Oneleet. We’re actively helping you level up your security and we want to encourage you to leverage these efforts as much as possible to unlock even more customers.
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/marketing-your-security.mdx
> +- **How to implement:** Include this achievement to your newsletter, share the page on LinkedIn and other socials.
```suggestion
- **How to implement:** Include this achievement in your newsletter, share the page on LinkedIn and other socials.
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/marketing-your-security.mdx
> +    5. Done! (if you’d like to change the title of the document, change the document name in your Evidence library)
```suggestion
    5. Done! (If you’d like to change the title of the document, update its name in your Evidence library)
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/marketing-your-security.mdx
> +If you’re in the fundraising and would like to add a slide in your pitchdeck outlining your security program, reach out to the Oneleet team and **we’ll create a tailored slide** for you.
```suggestion
If you’re fundraising and would like to add a slide to your pitch deck outlining your security program, reach out to the Oneleet team and **we’ll create a tailored slide** for you.
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/marketing-your-security.mdx
> +In this official announcement, you can choose many routes to promote your achievement. Wether you want to post on your socials, include it in your newsletter, email your users, or post a blog/article
```suggestion
In this official announcement, you can choose many routes to promote your achievement. Whether you want to post on your socials, include it in your newsletter, email your users, or post a blog/article about it. Below are a few examples of how to promote your milestone.
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/marketing-your-security.mdx
> +### **Write an article/blog post**
```suggestion
### **Write an article or blog post**
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/marketing-your-security.mdx
> +**Place your Compliance badge!**
```suggestion
**Place your compliance badge!**
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/personal-vs-company-workstations.mdx
> +Choosing the right devices for your business operations is very important for maintaining a strong security posture. While using company issued workstations is not a requirement for SOC 2 compliance—
```suggestion
Choosing the right devices for your business operations is very important for maintaining a strong security posture. While using company-issued workstations is not a requirement for SOC 2 compliance—you can achieve compliance with a Bring Your Own Device (BYOD) policy—we strongly recommend using dedicated company devices.
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/personal-vs-company-workstations.mdx
> +- **Increased attack surface**: Personal devices often have a multitude of applications installed—sometimes in the 100s—that are not necessary for business operations. Many of these are consumer-focu
this one is more nitish but chatGPT thinks it's clearer
```suggestion
- **Increased attack surface**: Personal devices often have a multitude of applications installed—sometimes in the 100s—that are not necessary for business operations. Many of these are consumer-focused apps that may not adhere to the same security standards as business applications.
```

2025-02-05 17:53 UTC, scherroman commented on pages/guides/personal-vs-company-workstations.mdx
> +- **Clearer boundaries**: Clear separation between work and personal activities reduces risk of data breaches.
```suggestion
- **Clearer boundaries**: Clear separation between work and personal activities reduces the risk of data breaches.
```

2025-02-06 18:27 UTC, scherroman approved these changes

2025-02-06 18:29 UTC, mnafees approved these changes

2025-06-03 19:13 UTC, merged